import { VideoItem, AIReport, ChannelAnalytics, YouTubeAccount, UserSettings, NotificationItem, PublishLog } from '../types';

export const initialYouTubeAccount: YouTubeAccount = {
  connected: true,
  channelId: 'UC_x5XG1OV2P6uZZ5FSM9Ttw',
  channelName: 'TechVision AI Lab',
  channelHandle: '@techvision_ai',
  avatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
  subscriberCount: 128400,
  videoCount: 84,
  connectedAt: '2025-01-15T10:00:00Z',
};

export const initialSettings: UserSettings = {
  geminiApiKeyConfigured: true,
  supabaseConfigured: true,
  youtubeConnected: true,
  notificationsEnabled: true,
  emailAlertsOnPublish: true,
  timezone: 'America/Los_Angeles (PST - UTC-8)',
  language: 'English (US)',
  autoGenerateMetadata: true,
  defaultVisibility: 'public',
};

export const initialVideos: VideoItem[] = [
  {
    id: 'vid-101',
    title: 'Building an Autonomous AI Agent with Gemini 3.5 & React',
    topic: 'Artificial Intelligence, Software Engineering, Autonomous Agents',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    visibility: 'public',
    status: 'published',
    youtubeId: 'dQw4w9WgXcQ',
    youtubeUrl: 'https://youtube.com/watch?v=dQw4w9WgXcQ',
    createdAt: '2026-07-20T14:30:00Z',
    updatedAt: '2026-07-20T14:35:00Z',
    metadata: {
      title: 'Building an Autonomous AI Agent in 2026! (Gemini 3.5 & React Step-by-Step)',
      description: `In this complete tutorial, learn how to build a fully autonomous AI coding and workflow agent using Google's latest Gemini 3.5 API and React. We cover architecture, tool calling, memory state, and production deployment.\n\n🔥 What You'll Learn:\n- Gemini 3.5 Function Calling Architecture\n- Building interactive WebSockets for real-time AI streams\n- Deploying to Cloud Run & Supabase\n\n📌 Resources & Code:\nGitHub Repo: https://github.com/techvision/ai-agent-starter\n\n#AIAgent #GeminiAI #ReactJS #FullStack #CodingTutorial`,
      tags: ['AI Agent', 'Gemini 3.5', 'React Tutorial', 'TypeScript', 'Autonomous AI', 'Google AI Studio', 'Software Development'],
      hashtags: ['#AIAgent', '#GeminiAI', '#ReactJS', '#Coding2026'],
      category: 'Science & Technology',
      playlistSuggestion: 'AI Masterclass & Tutorials 2026',
      chapters: [
        { timestamp: '00:00', title: 'Introduction & Demo' },
        { timestamp: '02:15', title: 'System Architecture & Tool Calling' },
        { timestamp: '07:40', title: 'Setting up Gemini 3.5 SDK' },
        { timestamp: '14:20', title: 'Building the Frontend React UI' },
        { timestamp: '21:05', title: 'Deploying & Testing Live Agent' },
      ],
      keywords: ['Gemini AI agent', 'Build AI app React', 'Google GenAI SDK 2026', 'AI agent tutorial'],
      callToAction: 'If this guide helped you, hit LIKE and SUBSCRIBE for weekly full-stack AI deep dives!',
      pinnedCommentSuggestion: '💬 What AI tool or agent do you want us to build next? Drop your ideas below, and top voted concept gets coded live!',
      endScreenSuggestion: 'Next Video: "Mastering Supabase Vector DB with Gemini Embeddings" + Subscribe Badge',
      cardsSuggestion: 'At 07:40: Link to "Gemini API Setup Guide" playlist',
    },
  },
  {
    id: 'vid-102',
    title: 'Top 10 Developer Productivity Tools You Must Use in 2026',
    topic: 'Developer Tools, Productivity, AI Software',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
    visibility: 'public',
    status: 'published',
    youtubeId: 'eYpXm1K40_w',
    youtubeUrl: 'https://youtube.com/watch?v=eYpXm1K40_w',
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-15T09:05:00Z',
    metadata: {
      title: 'Top 10 Essential Developer Tools for 2026 (Double Your Coding Speed! 🚀)',
      description: `Speed up your development workflow with these top 10 cutting-edge tools for developers in 2026. From AI pair programmers to instant Cloud SQL databases, these tools will transform your daily workflow.\n\n⏱️ Chapters:\n00:00 Intro\n01:30 Tool 1: ChannelOS AI\n04:15 Tool 2: Cursor 2.0\n08:00 Tool 3: Supabase CLI\n12:30 Summary & Verdict\n\n#DeveloperTools #Productivity #Coding #Tech`,
      tags: ['Developer Tools', 'Productivity 2026', 'Coding Tools', 'Software Engineering', 'AI Coding'],
      hashtags: ['#DeveloperTools', '#Productivity', '#Coding2026'],
      category: 'Science & Technology',
      playlistSuggestion: 'Developer Productivity Secrets',
      chapters: [
        { timestamp: '00:00', title: 'Overview' },
        { timestamp: '01:30', title: 'Tool 1: ChannelOS AI' },
        { timestamp: '04:15', title: 'Tool 2: Cursor & Claude' },
        { timestamp: '08:00', title: 'Tool 3: Supabase Cloud' },
        { timestamp: '12:30', title: 'Final Recommendations' },
      ],
      keywords: ['best developer tools 2026', 'developer productivity hacks', 'AI coding tools'],
      callToAction: 'Which tool are you downloading first? Let us know in the comments!',
      pinnedCommentSuggestion: '👇 Check out links to all 10 tools mentioned in the video description below!',
      endScreenSuggestion: 'Video: "Building an Autonomous AI Agent with Gemini 3.5"',
      cardsSuggestion: 'At 04:15: Card link to ChannelOS Platform',
    },
  },
  {
    id: 'vid-103',
    title: 'Full Stack Next.js 15 & Supabase Masterclass',
    topic: 'Next.js 15, Supabase, Postgres, Web Development',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreet.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    visibility: 'unlisted',
    status: 'publishing',
    createdAt: '2026-07-22T10:00:00Z',
    updatedAt: '2026-07-22T10:05:00Z',
    metadata: {
      title: 'Next.js 15 App Router & Supabase Complete Masterclass (Server Actions & RLS)',
      description: `Master modern full-stack web development with Next.js 15, Tailwind CSS, and Supabase! Build real-time apps with authentication, storage, and secure Row Level Security.\n\n#NextJS #Supabase #TypeScript #WebDev`,
      tags: ['Next.js 15', 'Supabase', 'PostgreSQL', 'Full Stack Masterclass'],
      hashtags: ['#NextJS', '#Supabase', '#FullStack'],
      category: 'Education',
      playlistSuggestion: 'Full Stack Masterclasses',
      chapters: [
        { timestamp: '00:00', title: 'Project Overview' },
        { timestamp: '05:00', title: 'Supabase Schema & RLS Setup' },
        { timestamp: '15:00', title: 'Next.js 15 App Router Routes' },
      ],
      keywords: ['Next.js 15 tutorial', 'Supabase crash course', 'Server Actions Nextjs'],
      callToAction: 'Subscribe for the next installment on Next.js 15 performance optimization!',
      pinnedCommentSuggestion: '🚀 Download the source code from our GitHub repository pinned in the description.',
      endScreenSuggestion: 'Next Video: "Building an Autonomous AI Agent"',
      cardsSuggestion: 'At 05:00: Link to Supabase SQL cheat sheet',
    },
  },
];

export const initialAIReports: AIReport[] = [
  {
    videoId: 'vid-101',
    videoTitle: 'Building an Autonomous AI Agent with Gemini 3.5 & React',
    overallScore: 94,
    seoScore: 96,
    ctrScore: 92,
    retentionScore: 91,
    thumbnailEffectiveness: 'High contrast visual with glowing Gemini node network draws 14.2% higher initial impressions click-through rate than industry average.',
    titleEffectiveness: 'Strong action verb "Building" combined with year anchor "2026" and clear parenthetical benefits "(Gemini 3.5 & React)" boosts organic search placement.',
    descriptionQuality: 'Includes clear timestamps, keyword-rich summaries, social links, and targeted hashtags.',
    strengths: [
      'Top-tier SEO keyword density for "Gemini 3.5 AI agent"',
      'High thumbnail contrast with clear code overlay',
      'Timestamps formatted cleanly for YouTube automated chapter indexing',
      'Effective engagement call-to-action in pinned comment',
    ],
    weaknesses: [
      'First 15 seconds retention could be higher by skipping static introduction slide',
      'Tags list could include more long-tail search queries',
    ],
    improvementSuggestions: [
      'Add a 5-second teaser clip at the very beginning before the intro intro animation',
      'Include 3 additional long-tail tags like "how to make AI agent React 2026"',
      'Test a high-contrast thumbnail variant with yellow headline font',
    ],
    nextVideoIdeas: [
      {
        title: 'Building a Multi-Agent AI Swarm with Gemini & Supabase Vector Search',
        rationale: 'High viewer interest in autonomous workflows and multi-agent coordination.',
        targetKeyword: 'Multi-agent AI Gemini tutorial',
      },
      {
        title: 'Gemini 3.5 vs Claude 3.7 vs GPT-4.5: Which AI API is Best for Developers?',
        rationale: 'Comparison videos perform exceptionally well in CTR and shareability.',
        targetKeyword: 'Gemini 3.5 vs Claude benchmark',
      },
      {
        title: 'Deploying Production AI Agents to Cloud Run for $0/month',
        rationale: 'Cost optimization is a major search query for indie developers and SaaS builders.',
        targetKeyword: 'Deploy AI app Cloud Run free tier',
      },
    ],
    bestUploadTime: 'Tuesdays & Thursdays at 11:00 AM PST (Peak audience activity window)',
    bestKeywords: ['Gemini 3.5 AI agent', 'Autonomous AI tutorial', 'React AI app build', 'Supabase Vector AI'],
    publishingStrategy: 'Publish video on Tuesday 11:00 AM PST, post a YouTube Community poll 2 hours prior, and cross-post a 45-second teaser to YouTube Shorts with a link to full video.',
    createdAt: '2026-07-20T15:00:00Z',
  },
  {
    videoId: 'vid-102',
    videoTitle: 'Top 10 Developer Productivity Tools You Must Use in 2026',
    overallScore: 88,
    seoScore: 90,
    ctrScore: 85,
    retentionScore: 87,
    thumbnailEffectiveness: 'Clean split screen layout showing developer tools icons. CTR is solid at 7.8%.',
    titleEffectiveness: 'Curiosity-driven listicle format "Top 10 Essential Developer Tools" creates urgency.',
    descriptionQuality: 'Good chapter timestamps and list summary.',
    strengths: [
      'Great listicle structure that keeps viewers watching past 50% mark',
      'Broad developer audience appeal',
    ],
    weaknesses: [
      'Thumbnail visual clutter on smaller mobile screens',
    ],
    improvementSuggestions: [
      'Simplify thumbnail text to 3 bold words maximum',
      'Add cards linking to detailed individual tool breakdown videos',
    ],
    nextVideoIdeas: [
      {
        title: '5 AI Tools That Replaced 80% of My Daily Coding Tasks',
        rationale: 'First-person personal narrative builds strong authority and curiosity.',
        targetKeyword: 'AI coding tools productivity',
      },
    ],
    bestUploadTime: 'Wednesdays at 2:00 PM PST',
    bestKeywords: ['developer tools 2026', 'best coding software', 'AI developer stack'],
    publishingStrategy: 'Promote top tools list on Twitter/X and Developer newsletters for instant seed views.',
    createdAt: '2026-07-15T10:00:00Z',
  },
];

export const initialAnalytics: Record<'7d' | '30d' | '90d' | 'lifetime', ChannelAnalytics> = {
  '7d': {
    timeframe: '7d',
    totalViews: 48250,
    viewsChange: 18.4,
    subscribersGained: 1420,
    subscribersChange: 24.1,
    averageCTR: 8.9,
    ctrChange: 1.2,
    avgViewDuration: '6m 18s',
    watchTimeHours: 5080,
    likes: 3890,
    comments: 642,
    shares: 412,
    impressions: 542000,
    estimatedRevenue: 385.50,
    viewsOverTime: [
      { date: 'Jul 16', views: 5400, watchTime: 580, subscribers: 180 },
      { date: 'Jul 17', views: 6100, watchTime: 640, subscribers: 210 },
      { date: 'Jul 18', views: 5800, watchTime: 610, subscribers: 195 },
      { date: 'Jul 19', views: 7200, watchTime: 790, subscribers: 240 },
      { date: 'Jul 20', views: 9800, watchTime: 1050, subscribers: 310 },
      { date: 'Jul 21', views: 7400, watchTime: 780, subscribers: 215 },
      { date: 'Jul 22', views: 6550, watchTime: 630, subscribers: 170 },
    ],
    trafficSources: [
      { name: 'YouTube Search', value: 48 },
      { name: 'Suggested Videos', value: 28 },
      { name: 'Browse Features', value: 14 },
      { name: 'External & Social', value: 7 },
      { name: 'Direct / Channel', value: 3 },
    ],
    topDemographics: [
      { ageGroup: '18-24', percentage: 28 },
      { ageGroup: '25-34', percentage: 52 },
      { ageGroup: '35-44', percentage: 14 },
      { ageGroup: '45+', percentage: 6 },
    ],
  },
  '30d': {
    timeframe: '30d',
    totalViews: 194800,
    viewsChange: 32.5,
    subscribersGained: 5840,
    subscribersChange: 29.8,
    averageCTR: 8.6,
    ctrChange: 1.8,
    avgViewDuration: '6m 02s',
    watchTimeHours: 19580,
    likes: 15400,
    comments: 2810,
    shares: 1840,
    impressions: 2260000,
    estimatedRevenue: 1560.00,
    viewsOverTime: [
      { date: 'W1 (Jun 22)', views: 38000, watchTime: 3800, subscribers: 1100 },
      { date: 'W2 (Jun 29)', views: 42000, watchTime: 4200, subscribers: 1250 },
      { date: 'W3 (Jul 06)', views: 51000, watchTime: 5200, subscribers: 1550 },
      { date: 'W4 (Jul 13)', views: 63800, watchTime: 6380, subscribers: 1940 },
    ],
    trafficSources: [
      { name: 'YouTube Search', value: 45 },
      { name: 'Suggested Videos', value: 31 },
      { name: 'Browse Features', value: 15 },
      { name: 'External & Social', value: 6 },
      { name: 'Direct / Channel', value: 3 },
    ],
    topDemographics: [
      { ageGroup: '18-24', percentage: 26 },
      { ageGroup: '25-34', percentage: 54 },
      { ageGroup: '35-44', percentage: 14 },
      { ageGroup: '45+', percentage: 6 },
    ],
  },
  '90d': {
    timeframe: '90d',
    totalViews: 542000,
    viewsChange: 41.2,
    subscribersGained: 16800,
    subscribersChange: 38.0,
    averageCTR: 8.3,
    ctrChange: 2.1,
    avgViewDuration: '5m 54s',
    watchTimeHours: 53200,
    likes: 42100,
    comments: 7900,
    shares: 5100,
    impressions: 6530000,
    estimatedRevenue: 4330.00,
    viewsOverTime: [
      { date: 'May 2026', views: 145000, watchTime: 14200, subscribers: 4200 },
      { date: 'Jun 2026', views: 182000, watchTime: 17900, subscribers: 5600 },
      { date: 'Jul 2026', views: 215000, watchTime: 21100, subscribers: 7000 },
    ],
    trafficSources: [
      { name: 'YouTube Search', value: 42 },
      { name: 'Suggested Videos', value: 34 },
      { name: 'Browse Features', value: 15 },
      { name: 'External & Social', value: 6 },
      { name: 'Direct / Channel', value: 3 },
    ],
    topDemographics: [
      { ageGroup: '18-24', percentage: 25 },
      { ageGroup: '25-34', percentage: 55 },
      { ageGroup: '35-44', percentage: 14 },
      { ageGroup: '45+', percentage: 6 },
    ],
  },
  'lifetime': {
    timeframe: 'lifetime',
    totalViews: 2840000,
    viewsChange: 112.0,
    subscribersGained: 128400,
    subscribersChange: 100.0,
    averageCTR: 8.1,
    ctrChange: 3.4,
    avgViewDuration: '5m 48s',
    watchTimeHours: 275000,
    likes: 218000,
    comments: 39400,
    shares: 26100,
    impressions: 35000000,
    estimatedRevenue: 22720.00,
    viewsOverTime: [
      { date: '2024 Q3', views: 320000, watchTime: 31000, subscribers: 14000 },
      { date: '2024 Q4', views: 480000, watchTime: 46000, subscribers: 22000 },
      { date: '2025 Q1', views: 610000, watchTime: 59000, subscribers: 28000 },
      { date: '2025 Q2', views: 720000, watchTime: 70000, subscribers: 32000 },
      { date: '2026 Q1-Q2', views: 710000, watchTime: 69000, subscribers: 32400 },
    ],
    trafficSources: [
      { name: 'YouTube Search', value: 40 },
      { name: 'Suggested Videos', value: 36 },
      { name: 'Browse Features', value: 15 },
      { name: 'External & Social', value: 6 },
      { name: 'Direct / Channel', value: 3 },
    ],
    topDemographics: [
      { ageGroup: '18-24', percentage: 24 },
      { ageGroup: '25-34', percentage: 56 },
      { ageGroup: '35-44', percentage: 14 },
      { ageGroup: '45+', percentage: 6 },
    ],
  },
};

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'success',
    title: 'Video Published Successfully',
    message: '"Building an Autonomous AI Agent with Gemini 3.5 & React" is now live on YouTube.',
    timestamp: '2 hours ago',
    read: false,
    link: 'https://youtube.com/watch?v=dQw4w9WgXcQ',
  },
  {
    id: 'notif-2',
    type: 'analytics',
    title: 'Analytics Milestone Reached',
    message: 'Your channel hit +1,420 new subscribers in the last 7 days! (+24.1%)',
    timestamp: '5 hours ago',
    read: false,
  },
  {
    id: 'notif-3',
    type: 'publishing',
    title: 'Gemini Metadata Generated',
    message: 'SEO Title, Description, Tags, and 5 Video Chapters auto-crafted for "Full Stack Masterclass".',
    timestamp: '1 day ago',
    read: true,
  },
];

export const initialPublishLogs: PublishLog[] = [
  {
    id: 'log-101',
    videoId: 'vid-101',
    videoTitle: 'Building an Autonomous AI Agent with Gemini 3.5 & React',
    action: 'Gemini Metadata Generation',
    status: 'success',
    details: 'Generated 11 metadata fields in 1.4s using gemini-3.6-flash model.',
    timestamp: '2026-07-20 14:31:02',
  },
  {
    id: 'log-102',
    videoId: 'vid-101',
    videoTitle: 'Building an Autonomous AI Agent with Gemini 3.5 & React',
    action: 'YouTube Data API Upload',
    status: 'success',
    details: 'Uploaded 184MB video file to YouTube servers via Resumable Upload protocol.',
    timestamp: '2026-07-20 14:33:45',
  },
  {
    id: 'log-103',
    videoId: 'vid-101',
    videoTitle: 'Building an Autonomous AI Agent with Gemini 3.5 & React',
    action: 'Thumbnail & Metadata Sync',
    status: 'success',
    details: 'Set high-res thumbnail, tags, category (28 - SciTech), and public visibility.',
    timestamp: '2026-07-20 14:35:10',
  },
  {
    id: 'log-104',
    videoId: 'vid-103',
    videoTitle: 'Full Stack Next.js 15 & Supabase Masterclass',
    action: 'YouTube OAuth Refresh Token',
    status: 'info',
    details: 'Successfully refreshed YouTube Data API v3 OAuth access token.',
    timestamp: '2026-07-22 10:01:12',
  },
];
